BOUT_TOP=../../..

SOURCEC = ImpuritySpecies.cxx Prad.cxx RateCoefficient.cxx sharedFunctions.cxx
SOURCEH		= $(SOURCEC:%.cxx=%.hxx) json.hxx

MODULE_DIR	= ..
SUB_NAME	= atomicpp
TARGET		= sd1d

include $(BOUT_TOP)/make.config
